import React, {useMemo,useState} from 'react';
import {ArrowRight, CaretRight, Info, MagnifyingGlass, SquaresFour, Buildings, TreeStructure} from '@phosphor-icons/react';
import {useAtlas} from './context';
import {number,displayName,simplify,discoveryLabel,hasScope} from './data';
import {External} from './ui';

export const BROWSE_MODES=[['industry','산업별',SquaresFour],['organization','기업 유형별',Buildings],['group','그룹별',TreeStructure]];

export function Discovery(){
 const {state,data,all,identityIndex,discover,change,setDialog}=useAtlas();
 const {categories,organizations,groups}=data.manifest.discovery;
 const [groupQuery,setGroupQuery]=useState(''),[showAll,setShowAll]=useState(false);
 const browsing=!hasScope(state)&&state.browse!=='all';
 const groupList=groups.filter(g=>simplify(g.name+' '+g.officialName).includes(simplify(groupQuery)));
 const title=state.entity?`${identityIndex.entities.get(state.entity)?.[0]?.identity.name||'법인 연결'} · 명부 모아보기`:state.group?`${groups.find(g=>g.id===state.group)?.name||state.group} 계열사`:state.industry?discoveryLabel(data.manifest,state.industry):state.organization?organizations.find(o=>o.id===state.organization)?.name:state.facets.category?discoveryLabel(data.manifest,state.facets.category):state.facets.industry||'기업·기관 찾기';
 const groupUnknown=useMemo(()=>all.filter(r=>r.sourceId==='large'&&r.group===state.group&&r.industry==='unknown').length,[all,state.group]);
 const subindustries=useMemo(()=>[...new Set(all.filter(r=>(!state.industry||r.industry===state.industry)&&(!state.group||(r.sourceId==='large'&&r.group===state.group))).map(r=>r.industryLabel).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ko')),[all,state.industry,state.group]);
 return <section className={'discovery '+(!browsing?'discovery-compact':'')} aria-label="카테고리로 탐색">
   <div className="browse-tabs" aria-label="탐색 시작점">{BROWSE_MODES.map(([id,label,Icon])=><button key={id} aria-pressed={state.browse===id} className={state.browse===id?'active':''} onClick={()=>discover(id)}><Icon size={20}/>{label}</button>)}<button className={state.browse==='all'?'active':''} aria-pressed={state.browse==='all'} onClick={()=>discover('all')}>전체 명부</button></div>
   {browsing?<>
    <div className="discovery-heading"><h2>{state.browse==='group'?'익숙한 그룹에서, 새로운 계열사로':state.browse==='organization'?'어떤 유형의 기업을 찾으세요?':'관심 가는 산업부터 골라보세요'}</h2><button className="text-button" onClick={()=>setDialog('sources')}><Info size={16}/>수록 범위</button></div>
    {state.browse==='industry'&&<><div className="industry-grid">{categories.map((c,i)=><button className={'industry-tile '+(c.id==='unknown'?'unknown':'')} key={c.id} onClick={()=>discover('industry',{industry:c.id})}><div><span className="category-index">{String(i+1).padStart(2,'0')}</span><strong>{c.name}</strong><CaretRight size={17}/></div><p>{c.description}</p></button>)}</div><p className="coverage-line">산업을 고른 뒤 세부 업종과 기업 유형으로 좁혀볼 수 있습니다. 산업 미확인 명부도 함께 탐색하세요.</p></>}
    {state.browse==='organization'&&<><div className="organization-grid">{organizations.map(o=><button key={o.id} onClick={()=>discover('organization',{organization:o.id})}><h3>{o.name}<ArrowRight size={19}/></h3><p>{o.description}</p><span>{number(o.count)}개 출처 항목</span></button>)}</div><p className="coverage-line">기관의 법적 형태와 수록 명부를 기준으로 한 탐색 경로입니다. 상장사와 기업집단 계열사는 서로 겹칠 수 있습니다.</p></>}
    {state.browse==='group'&&<><div className="group-toolbar"><p><strong>{groups.length}개 기업집단</strong> · 공정위 2026.05.01 명부 순서</p><label><MagnifyingGlass size={18}/><input aria-label="기업집단 검색" placeholder="삼성, SK, 현대자동차…" value={groupQuery} onChange={e=>setGroupQuery(e.target.value)}/></label></div><div className="group-grid">{groupList.slice(0,showAll||groupQuery?undefined:12).map(g=><button key={g.id} onClick={()=>discover('group',{group:g.id})}><div><h3>{g.name}</h3><span>{number(g.count)}개 명부 항목 <CaretRight size={15}/></span></div><p>{g.examples.map(displayName).join(' · ')}</p></button>)}</div>{!groupList.length&&<p className="empty-state">일치하는 기업집단이 없습니다.</p>}{!groupQuery&&<button className="button group-expand" onClick={()=>setShowAll(v=>!v)}>{showAll?'12개 그룹으로 접기':`${groups.length}개 그룹 모두 보기`}</button>}<p className="coverage-line">모든 계열사가 같은 사업을 하는 것은 아닙니다. 그룹을 고른 뒤 산업별로 다시 좁혀보세요.</p></>}
    <div className="discovery-footer"><div><strong>자료의 범위도 함께 확인하세요</strong><p>전국 모든 기업을 모은 서비스는 아닙니다. 서로 다른 7개 명부를 연결해 탐색합니다.</p></div><button className="text-button" onClick={()=>setDialog('sources')}>어디까지 담았나요? <ArrowRight size={17}/></button></div>

   </>:<><nav className="discovery-breadcrumb" aria-label="현재 탐색 경로"><button onClick={()=>discover(state.browse==='all'?'industry':state.browse)}>카테고리 선택</button><CaretRight size={14}/><span>{title}</span></nav><div className="scope-heading"><h2>{title}</h2>{state.group&&<span>공정위 계열사 명부 · 산업을 고르면 교차 탐색</span>}</div>{state.industry&&<p className="scope-description">{categories.find(c=>c.id===state.industry)?.description}</p>}{state.industry==='finance'&&<div className="scope-note">은행·증권·보험과 지역 조합·금고를 함께 담고 있습니다. <button onClick={()=>discover('industry',{industry:'finance',organization:'cooperative'})}>지역 조합·금고</button>는 별도로 좁혀볼 수 있습니다.</div>}</>}
 {!browsing&&state.group&&groupUnknown>0&&<p className="coverage-line">이 그룹의 {groupUnknown}개 항목은 산업 근거가 아직 없습니다. <button className="text-button" onClick={()=>change({industry:'unknown',subindustry:'',detail:''})}>산업 미확인 계열사 보기</button></p>}{!browsing&&<div className="scope-refinement"><span>더 좁혀보기</span>{state.industry?<label><span className="sr-only">결과 내 세부 업종</span><select aria-label="결과 내 세부 업종" value={state.subindustry} onChange={e=>change({subindustry:e.target.value,detail:''})}><option value="">모든 세부 업종</option>{subindustries.map(s=><option key={s}>{s}</option>)}</select></label>:<label><span className="sr-only">결과 내 산업</span><select aria-label="결과 내 산업" value={state.industry} onChange={e=>change({industry:e.target.value,subindustry:'',detail:''})}><option value="">모든 산업</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}{!state.group&&<label><span className="sr-only">결과 내 기업 유형</span><select aria-label="결과 내 기업 유형" value={state.organization} onChange={e=>change({organization:e.target.value,detail:''})}><option value="">모든 기업 유형</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}</div>}
 </section>;
}
