import React, { useEffect, useMemo, useRef } from 'react';
import { MagnifyingGlass, ChartBar, BookmarkSimple, X, CaretDown, CaretLeft, CaretRight, SlidersHorizontal, LinkSimple, MapPin, FileText, Buildings, Info, ListChecks } from '@phosphor-icons/react';
import { number, displayName, hasScope, discoveryLabel, CLASSIFICATIONS, regionValues, CHART_DIMENSIONS } from './data';
import { Discovery, BROWSE_MODES } from './Discovery';
import { useAtlas } from './context';
import { External, Tag, dateText } from './ui';
import { CompanyLinks } from './CompanyLinks';
const PAGE_SIZE=20;
function usePanelFocus(ref,active,onClose,query){
  const close=useRef(onClose);close.current=onClose;
  useEffect(()=>{if(!active||!window.matchMedia(query).matches||!ref.current)return;
    const panel=ref.current,previous=document.activeElement;
    const focusable=()=>[...panel.querySelectorAll('button,a[href],input,select,textarea')].filter(el=>!el.disabled&&el.getClientRects().length);
    focusable()[0]?.focus();
    const key=e=>{if(e.key==='Escape'){e.preventDefault();close.current();}else if(e.key==='Tab'){const elements=focusable(),first=elements[0],last=elements.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};
    panel.addEventListener('keydown',key);return()=>{panel.removeEventListener('keydown',key);if(previous?.isConnected)previous.focus();};
  },[active,query,ref]);
}

export function Sidebar(){
  const {state,all,data,change,discover,mobileFilters,setMobileFilters,setDialog}=useAtlas();
  const panel=useRef(null);usePanelFocus(panel,mobileFilters,()=>setMobileFilters(false),'(max-width: 720px)');
  const regions=useMemo(()=>[...new Set(all.flatMap(r=>regionValues(r.region)))].sort((a,b)=>a.localeCompare(b,'ko')),[all]);
  const industries=data.manifest.discovery.categories,orgs=data.manifest.discovery.organizations;
  const subindustries=useMemo(()=>[...new Set(all.filter(r=>r.industry===state.industry&&(!state.organization||r.organization===state.organization)&&(!state.group||(r.sourceId==='large'&&r.group===state.group))).map(r=>r.industryLabel).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ko')),[all,state.industry,state.organization,state.group]);
  return <aside ref={panel} className={'filters '+(mobileFilters?'filters-open':'')} aria-label="탐색 필터"><div className="mobile-filter-title"><strong>탐색 조건</strong><button className="icon-button" aria-label="필터 닫기" onClick={()=>setMobileFilters(false)}><X size={22}/></button></div>
    <section className="filter-intro"><h2>탐색 조건</h2><p>산업과 기업 유형을 함께 선택해 관심 범위를 좁혀보세요.</p></section>
    <section className="filter-section compact"><label htmlFor="industry-filter">산업</label><select id="industry-filter" value={state.industry} onChange={e=>change({industry:e.target.value,subindustry:'',detail:''})}><option value="">모든 산업</option>{industries.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></section>
    {state.industry&&subindustries.length>0&&<section className="filter-section compact"><label htmlFor="subindustry-filter">세부 업종 (원문)</label><select id="subindustry-filter" value={state.subindustry} onChange={e=>change({subindustry:e.target.value,detail:''})}><option value="">전체 세부 업종</option>{subindustries.map(s=><option key={s}>{s}</option>)}</select></section>}
    <section className="filter-section compact"><label htmlFor="organization-filter">기업·기관 유형</label><select id="organization-filter" value={state.organization} onChange={e=>change({organization:e.target.value,subindustry:'',detail:''})}><option value="">모든 유형</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></section>
    <section className="filter-section compact"><label htmlFor="region-filter">명부 지역</label><select id="region-filter" value={state.region} onChange={e=>change({region:e.target.value})}><option value="">전체 지역</option>{regions.map(r=><option key={r}>{r}</option>)}<option value="unknown">지역 미기재</option></select><p className="filter-caption">소재지·관할 기준. 입사 후 배치와 다릅니다.</p></section>
    <details className="additional-filters"><summary>자료 조건 더 보기</summary><section className="filter-section compact"><label htmlFor="source-filter">명부 출처</label><select id="source-filter" value={state.source} onChange={e=>change({source:e.target.value})}><option value="">전체 출처</option>{data.manifest.sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></section><label className="filter-option"><input type="checkbox" checked={!!state.status} onChange={e=>change({status:e.target.checked?'linked':''})}/><span>공식 공고 연결 있음</span></label><p className="filter-caption">현재 모집이 아닌 과거 확인자료 포함</p></details>
    <button className="text-button source-button" onClick={()=>setDialog('sources')}><Info size={16}/> 수록 범위·집계 기준</button>
    {mobileFilters&&<button className="button primary apply-mobile-filters" onClick={()=>setMobileFilters(false)}>조건 적용해서 보기</button>}
  </aside>;
}

export function Detail(){
  const {selected,data,sourceMap,state,change,discover,savedIds,toggleSave,toggleCompare}=useAtlas();
  const panel=useRef(null);usePanelFocus(panel,selected?.id,()=>change({detail:''}),'(max-width: 1000px)');
  if(!selected)return null;const notices=data.evidence[selected.id]||[];
  return <aside ref={panel} className="detail-panel" aria-label={`${displayName(selected.name)} 상세정보`}><button className="detail-close icon-button" aria-label="상세정보 닫기" onClick={()=>change({detail:''})}><X size={23}/></button><h2>{displayName(selected.name)}</h2><p className="detail-subtitle">{selected.ministry||sourceMap[selected.sourceId]?.name}</p><div className="tags"><Tag blue>{discoveryLabel(data.manifest,selected.industry)}</Tag>{selected.types.map(t=><Tag key={t}>{t}</Tag>)}</div>
    <section className="detail-section business-detail"><h3>어떤 일을 하는 곳인가요?</h3><p>{selected.business||'사업 내용은 아직 연결하지 못했습니다. 아래 기관 원문에서 확인할 수 있습니다.'}</p><dl className="fact-list"><div><dt>원문 업종</dt><dd>{selected.industryLabel||'미확인'}</dd></div>{selected.group&&<div><dt>기업집단</dt><dd>{selected.group}<small>{selected.groupBasis}</small><button className="text-button" onClick={()=>discover('group',{group:selected.group})}>계열사 함께 보기</button></dd></div>}</dl><p className="classification-note"><strong>{CLASSIFICATIONS[selected.classification]}</strong> · {selected.classificationNote}</p>{selected.industrySource&&<External href={selected.industrySource}>분류 근거 원문 · {selected.industryDate||'기준일 미기재'}</External>}{selected.businessSource&&selected.businessSource!==selected.industrySource&&<External href={selected.businessSource}>사업·제품 설명 원문</External>}{selected.industry!=='unknown'&&<button className="text-button related-industry" onClick={()=>discover('industry',{industry:selected.industry})}>같은 산업 둘러보기 <CaretRight size={15}/></button>}</section>
    <CompanyLinks/><section className="detail-section"><h3>기본정보와 확인할 내용</h3><dl className="fact-list"><div><dt><Buildings size={18}/>명부 출처</dt><dd>{sourceMap[selected.sourceId]?.provider}</dd></div><div><dt><FileText size={18}/>명부 기준일</dt><dd>{dateText(selected.asOf)}</dd></div><div><dt><MapPin size={18}/>{selected.region?'명부 지역':'소재지(원문)'}</dt><dd>{selected.region||selected.address||'미기재'}<small>{selected.regionKind} · 실제 배치지역은 공고에서 확인</small></dd></div>{selected.address&&<div><dt>기재 주소</dt><dd>{selected.address}<small>{selected.identity?'DART 기업개황':'명부 기재값'} · 실근무지 별도 확인</small></dd></div>}<div><dt><ListChecks size={18}/>직무·응시요건</dt><dd>지원 회차 공고에서 확인</dd></div></dl>{selected.types.includes('직영')&&<p className="notice-inline">지방자치단체 직영사업입니다. 실제 고용주와 채용 절차를 별도로 확인하세요.</p>}</section>
    <section className="detail-section"><div className="section-title"><h3>연결된 공식 공고</h3><span className="small-count">{notices.length}건</span></div>{notices.length?notices.map((n,i)=><article className="notice-card" key={n.url+i}><Tag>과거 확인자료</Tag><External href={n.url}>{n.title||'공식 채용공고 원문'}</External><p>{n.entry||'채용구분 미확인'} · {n.employment||'고용형태 미확인'}</p><p>접수 {n.period||'미확인'}</p><p>{n.role||'직무 미확인'} · {n.region||'근무지 미확인'}</p>{n.headcountText&&<p>공고 전체 인원 {n.headcountText}<small>해당 직무 신입 인원과 다를 수 있습니다.</small></p>}<small>원문 확인 {n.checked||'미기재'} · 최신 정정 확인 필요</small></article>):<p className="empty-detail">저장 자료에 연결된 공고가 없습니다.<br/>채용이 없다는 뜻은 아닙니다.</p>}</section>
    <section className="detail-section"><h3>관련 링크</h3><External href={selected.sourceUrl}><LinkSimple size={18}/> 명부·기관 원문</External>{selected.homepage&&<External href={selected.homepage}>공식 홈페이지</External>}</section><div className="detail-actions"><button className="button" onClick={()=>toggleSave(selected.id)}><BookmarkSimple weight={savedIds.has(selected.id)?'fill':'regular'} size={19}/>{savedIds.has(selected.id)?'저장됨':'내 목록에 저장'}</button><button className="button primary" onClick={()=>toggleCompare(selected.id)}><ChartBar size={18}/>{state.compare.includes(selected.id)?'비교에서 빼기':'비교에 추가'}</button></div><p className="detail-footnote">명부 등록은 현재 채용이나 지원 적격을 의미하지 않습니다.</p>
  </aside>;
}

export function Explore(){
  const {state,input,setInput,data,selected,sourceMap,identityIndex,filtered,change,reset,share,setMobileFilters,page,setPage,toggleCompare,toggleSave,savedIds,setTab,setDialog}=useAtlas();
  const showingResults=hasScope(state)||state.browse==='all';
  const entityRows=identityIndex.entities.get(state.entity)||[];
  const chips=[['q',state.q],['entity',state.entity?`같은 법인: ${entityRows[0]?.identity.name||'일치 항목 없음'}`:''],...Object.entries(state.facets).map(([key,value])=>['facet:'+key,`${CHART_DIMENSIONS[key]}: ${key==='category'?discoveryLabel(data.manifest,value):value}`]),['industry',state.industry?discoveryLabel(data.manifest,state.industry):''],['subindustry',state.subindustry],['organization',data.manifest.discovery.organizations.find(o=>o.id===state.organization)?.name],['group',state.group],['source',sourceMap[state.source]?.name],['region',state.region==='unknown'?'지역 미기재':state.region],['type',state.type],['status',state.status?'공고 연결 있음':'']].filter(([,v])=>v);
  const totalPages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)),currentPage=Math.min(page,totalPages);
  return <><section className="search-area"><div className="search-intro"><div><p className="eyebrow">DISCOVER · UNDERSTAND · COMPARE</p><h1>산업에서 발견하고, 근거로 비교하세요.</h1><p>어떤 일을 하는 기업인지 살펴보고, 나만의 관심 후보를 정리하세요.</p></div><button className="text-button intro-help" onClick={()=>setDialog('about')}>처음 오셨나요? <Info size={17}/></button></div><form className="search-form" onSubmit={e=>{e.preventDefault();change({q:input,detail:'',browse:input?state.browse:'all'});setMobileFilters(false);}}><MagnifyingGlass size={24}/><input aria-label="기업명, 그룹, 업종·제품으로 검색" placeholder="기업명, 그룹, 업종·제품으로 검색" value={input} onChange={e=>setInput(e.target.value)}/>{input&&<button type="button" className="icon-button search-clear" aria-label="검색어 지우기" onClick={()=>{setInput('');change({q:''});}}><X size={18}/></button>}<button type="submit" className="search-submit">검색</button></form><button className="button filter-mobile-toggle discovery-filter-toggle" onClick={()=>setMobileFilters(true)}><SlidersHorizontal size={17}/>탐색 조건</button></section><Discovery/>
    {showingResults?<div className={'explore-layout '+(!selected?'no-detail':'')}><section className="results" aria-label="탐색 결과"><div className="results-toolbar"><div className="results-count">검색 결과 <strong>{number(filtered.length)}</strong><span>출처 항목</span></div><button className="button filter-mobile-toggle" onClick={()=>setMobileFilters(true)}><SlidersHorizontal size={17}/>필터</button><button className="text-button result-chart-link" onClick={()=>{change({chartFiltered:true,chartSource:state.source||filtered[0]?.sourceId||'listed'});setTab('charts');}}><ChartBar size={17}/>분포 보기</button><label className="sort-label"><span className="sr-only">정렬</span><select value={state.sort} onChange={e=>change({sort:e.target.value})}><option value="context">사업정보 있는 순</option><option value="reviewed">공고 확인일순</option><option value="name">이름순</option></select></label></div><div className="filter-chips">{chips.map(([k,label])=><button key={k} className="chip" onClick={()=>{change({...(k.startsWith('facet:')?{facets:Object.fromEntries(Object.entries(state.facets).filter(([key])=>key!==k.slice(6)))}:{[k]:''}),...(k==='industry'?{subindustry:''}:{}),detail:''});if(k==='q')setInput('');}}>{label}<X size={14}/><span className="sr-only"> 필터 해제</span></button>)}{chips.length>0&&<button className="text-button" onClick={reset}>모든 필터 초기화</button>}<button className="icon-button share-button" onClick={share} aria-label="현재 검색 링크 복사"><LinkSimple size={19}/></button></div>
      <div className="list-heading"><span>비교</span><span>기업·기관 / 하는 일</span><span>자료</span><span>명부 기준일</span><span>저장</span></div>{filtered.length===0?<div className="empty-state"><MagnifyingGlass size={34}/><h2>조건에 맞는 항목이 없습니다</h2><p>검색어를 짧게 입력하거나 필터를 해제해 보세요.</p><button className="button" onClick={reset}>필터 초기화</button></div>:<div className="result-list">{filtered.slice((currentPage-1)*PAGE_SIZE,currentPage*PAGE_SIZE).map(r=><article className={'result-row '+(state.compare.includes(r.id)?'compared ':'')+(r.id===state.detail?'opened':'')} key={r.id}><input type="checkbox" checked={state.compare.includes(r.id)} onChange={()=>toggleCompare(r.id)} aria-label={`${displayName(r.name)} 비교 선택`}/><button className="result-name" onClick={()=>change({detail:r.id})}><strong>{displayName(r.name)}</strong><span className="row-context">{discoveryLabel(data.manifest,r.industry)} · {r.group||sourceMap[r.sourceId]?.name}</span><span className="row-business">{r.business||r.industryLabel||'사업 내용 미확인'}</span><span className="row-provenance">{sourceMap[r.sourceId]?.provider} · {CLASSIFICATIONS[r.classification]}</span>{r.identity&&(identityIndex.entities.get(r.identity.key)?.length||0)>1&&<span className="row-entity">같은 법인 · 다른 항목 {identityIndex.entities.get(r.identity.key).length-1}개 연결</span>}</button><span className={'evidence-label '+(r.evidenceCount?'has-evidence':'')}>{r.evidenceCount?'공식 공고':'명부 자료'}</span><span className="row-date">{dateText(r.asOf)}{r.checked&&<small>공고 확인 {dateText(r.checked)}</small>}</span><button className={'row-save icon-button '+(savedIds.has(r.id)?'saved':'')} onClick={()=>toggleSave(r.id)} aria-pressed={savedIds.has(r.id)} aria-label={`${displayName(r.name)} ${savedIds.has(r.id)?'저장됨':'저장'}`}><BookmarkSimple size={21} weight={savedIds.has(r.id)?'fill':'regular'}/></button></article>)}</div>}
      <div className="pagination"><span>{number(filtered.length)}항목 중 {filtered.length?number((currentPage-1)*PAGE_SIZE+1):0}–{number(Math.min(currentPage*PAGE_SIZE,filtered.length))}</span><button className="icon-button" disabled={currentPage===1} aria-label="이전 페이지" onClick={()=>{setPage(p=>p-1);window.scrollTo({top:0});}}><CaretLeft size={20}/></button><strong>{currentPage} / {number(totalPages)}</strong><button className="icon-button" disabled={currentPage===totalPages} aria-label="다음 페이지" onClick={()=>{setPage(p=>p+1);window.scrollTo({top:0});}}><CaretRight size={20}/></button></div><p className="list-disclaimer">같은 기관이 다른 출처에 다시 나타날 수 있습니다. 항목 수는 고유 고용주 수가 아닙니다.</p>
    </section><Detail/></div>:<Detail/>}
  </>;
}
