import React, { useMemo, useRef, useState } from 'react';
import { MagnifyingGlass, ChartBar, BookmarkSimple, X, DownloadSimple, UploadSimple, LinkSimple, NotePencil, Info, ArrowRight, Table, ListChecks } from '@phosphor-icons/react';
import { discoveryLabel,number,displayName,simplify,download } from './data';
import { useAtlas } from './context';
import { External,Tag } from './ui';

export function SavedPage(){
  const {data,saved,byId,sourceMap,state,setTab,setDialog,change,toggleCompare,updateNote,importBackup,notify}=useAtlas();const input=useRef(null);
  const [query,setQuery]=useState(''),[onlyNext,setOnlyNext]=useState(false);
  const visible=saved.filter(item=>(!onlyNext||item.next.trim())&&simplify([byId.get(item.id)?.name,item.note,item.next].join(' ')).includes(simplify(query)));
  return <section className="workspace-page"><div className="page-title"><div><p className="eyebrow">MY COLLECTION</p><h1>관심에서, 다음 행동으로</h1><p>저장한 후보 {number(saved.length)}개 · 이 브라우저에만 저장됩니다.</p></div><div className="button-group"><button className="button" onClick={()=>input.current.click()}><UploadSimple size={17}/>복원</button><button className="button primary" disabled={!saved.length} onClick={()=>{download(JSON.stringify({version:1,exportedAt:new Date().toISOString(),items:saved},null,2),'SCOPE_내목록_백업.json','application/json');notify('내 목록 백업 파일이 준비됐습니다.');}}><DownloadSimple size={17}/>백업</button><input className="sr-only" ref={input} type="file" accept="application/json,.json" onChange={importBackup} aria-label="내 목록 백업 파일"/></div></div><div className="context-note"><Info size={19}/><p>메모는 서버에 전송하지 않습니다. 브라우저 데이터를 지우기 전에는 백업하세요. 복원 시 같은 후보의 메모는 백업 값으로 반영됩니다.</p></div>
    {saved.length>0&&<div className="saved-toolbar"><label className="saved-search"><MagnifyingGlass size={19}/><input aria-label="내 목록 검색" placeholder="기업명·메모·다음 할 일 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="checkbox-label"><input type="checkbox" checked={onlyNext} onChange={e=>setOnlyNext(e.target.checked)}/>다음 할 일이 있는 후보</label><span>{visible.length} / {saved.length}개</span></div>}
    {!saved.length?<div className="empty-state"><BookmarkSimple size={42}/><h2>관심 있는 곳부터 하나 담아보세요</h2><p>기업 목록이나 상세정보에서 ‘내 목록에 저장’을 누르면 이곳에 모입니다.</p><button className="button primary" onClick={()=>setTab('explore')}>기업 탐색하기</button></div>:visible.length===0?<div className="empty-state"><h2>일치하는 저장 후보가 없습니다</h2><button className="button" onClick={()=>{setQuery('');setOnlyNext(false);}}>목록 검색 초기화</button></div>:<div className="saved-grid">{visible.map(item=>{const r=byId.get(item.id);return <article className="saved-card" key={item.id}><div className="saved-card-head"><div><Tag blue>{r?discoveryLabel(data.manifest,r.industry):'이전 명부 항목'}</Tag><h2>{r?displayName(r.name):item.id}</h2><p>{r?sourceMap[r.sourceId]?.name:'현재 명부에 없으며 메모는 보존됩니다.'}</p></div><button className="icon-button" aria-label={`${r?displayName(r.name):item.id} 저장 제거`} onClick={()=>setDialog({remove:item.id,name:r?displayName(r.name):item.id})}><X size={20}/></button></div><label><NotePencil size={16}/>메모<textarea value={item.note} maxLength={20000} placeholder="관심을 가진 이유, 비교할 조건을 적어보세요." onChange={e=>updateNote(item.id,'note',e.target.value)}/></label><label><ListChecks size={16}/>다음에 확인할 일<input value={item.next} maxLength={2000} placeholder="예: 주요 사업과 공식 홈페이지 확인" onChange={e=>updateNote(item.id,'next',e.target.value)}/></label>{r&&<div className="saved-card-actions"><button className="text-button" onClick={()=>{change({detail:r.id,browse:'all'});setTab('explore');}}>상세정보 <ArrowRight size={16}/></button><button className="button" onClick={()=>toggleCompare(r.id)}><ChartBar size={16}/>{state.compare.includes(r.id)?'비교에서 빼기':'비교에 추가'}</button></div>}</article>;})}</div>}
  </section>;
}
